vars: {
  d2-config: {
    layout-engine: elk
    theme-id: 200
  }
}

vavilon: Vavilon {
  files: FS {
    fs: |`code
      /var/
      |--vavilon/
         |--proto
         |--proto.d/
         |--cipher
         |--cipher.d/
         |--srv-modules/
            |--conf
            |--conf.d/
               |--core/
               |--stat/
               |--monitor/
               |--ctrl-panel/
            |--gui
            |--gui.d/
               |--ctrl-panel/
               |--stat/
               |--monitor/
            |--logical
            |--logical.d/
               |--core/
               |--ctrl-panel/
               |--stat/
               |--monitor/
         |--clnt-modules/
         |--modules
         |--Vavilon.py
    `| {shape: code; grid-rows: 1}

    grid-columns: 2
    proto: Protocols {
      grid-columns: 1
      protofile: proto
      protod: proto.d/
    }
  }

  srv: Server {
  }

  clnt: Client {
  }

}
