vars: {
  d2-config: {
    layout-engine: elk
    theme-id: 200
  }
}

vavilon: Vavilon {
  files: FS {
    fs: |`code
      /var/
      |--vavilon/
         |--proto
         |--proto.d/
         |--cipher
         |--cipher.d/
    `| {shape: code; grid-rows: 1}

    grid-columns: 2
    proto: Protocols {
      grid-columns: 1
      protofile: proto
      protod: proto.d/
    }
  }

  srv: Server {
  }

  clnt: Client
}
